export const CHANGE_SEARCH_FIELD='CHANGE_SEARCH_FIELD';
export const REQUEST_PHOTOS_PENDING='REQUEST_PHOTOS_PENDING';
export const REQUEST_PHOTOS_SUCCESS='REQUEST_PHOTOS_SUCCESS';
export const REQUEST_PHOTOS_FAILED='REQUEST_PHOTOS_PENDING';

export const REQUEST_CATEGORIES_PENDING='REQUEST_CATEGORIES_PENDING';
export const REQUEST_CATEGORIES_SUCCESS='REQUEST_CATEGORIES_SUCCESS';
export const REQUEST_CATEGORIES_FAILED='REQUEST_CATEGORIES_PENDING';